from app.schemas.domain.event import EventType


class EventTypes:
    DOWNLOAD_COMPLETED = EventType.DOWNLOAD_COMPLETED
    DOWNLOAD_FAILED = EventType.DOWNLOAD_FAILED
    DOWNLOAD_TASK_DOWNLOADER_CHANGE_FAILED = EventType.DOWNLOAD_TASK_DOWNLOADER_CHANGE_FAILED
    DOWNLOAD_TASK_STORAGE_CHANGE_FAILED = EventType.DOWNLOAD_TASK_STORAGE_CHANGE_FAILED
    MEDIA_IMPORT_COMPLETED = EventType.MEDIA_IMPORT_COMPLETED
    MEDIA_IMPORT_FAILED = EventType.MEDIA_IMPORT_FAILED
    MEDIA_SERVER_SYNC_COMPLETED = EventType.MEDIA_SERVER_SYNC_COMPLETED
    MEDIA_SERVER_SYNC_FAILED = EventType.MEDIA_SERVER_SYNC_FAILED
    DANMU_GENERATE_COMPLETED = EventType.DANMU_GENERATE_COMPLETED
    DANMU_GENERATE_FAILED = EventType.DANMU_GENERATE_FAILED
    MEDIA_DELETED = EventType.MEDIA_DELETED
    LIBRARY_FILE_MISSING = EventType.LIBRARY_FILE_MISSING

    SUBSCRIPTION_ENDED_MOVIE_COMPLETED = EventType.SUBSCRIPTION_ENDED_MOVIE_COMPLETED
    SUBSCRIPTION_ENDED_MOVIE_DOWNLOADING_COMPLETED = EventType.SUBSCRIPTION_ENDED_MOVIE_DOWNLOADING_COMPLETED
    SUBSCRIPTION_ENDED_MOVIE_TARGET_COMPLETED = EventType.SUBSCRIPTION_ENDED_MOVIE_TARGET_COMPLETED
    SUBSCRIPTION_ENDED_TV_COMPLETED = EventType.SUBSCRIPTION_ENDED_TV_COMPLETED
    SUBSCRIPTION_ENDED_TV_UPGRADE_COMPLETED = EventType.SUBSCRIPTION_ENDED_TV_UPGRADE_COMPLETED
    SUBSCRIPTION_ENDED_TV_TARGET_COMPLETED = EventType.SUBSCRIPTION_ENDED_TV_TARGET_COMPLETED

    FOLLOW_RELEASED = EventType.FOLLOW_RELEASED
    FOLLOW_DIGITAL_RELEASED = EventType.FOLLOW_DIGITAL_RELEASED
    FOLLOW_PHYSICAL_RELEASED = EventType.FOLLOW_PHYSICAL_RELEASED

    ADDON_RUN_STARTED = EventType.ADDON_RUN_STARTED
    ADDON_RUN_COMPLETED = EventType.ADDON_RUN_COMPLETED
    ADDON_RUN_FAILED = EventType.ADDON_RUN_FAILED
    ADDON_RUN_SKIPPED = EventType.ADDON_RUN_SKIPPED

    NOTIFICATION_SENT = EventType.NOTIFICATION_SENT
    NOTIFICATION_FAILED = EventType.NOTIFICATION_FAILED

    @staticmethod
    def command(command_type: str, phase: str) -> str:
        return f"command.{command_type}.{phase}"
