export const ResourceTagType = Object.freeze({
  UNMATCHED: 'unmatched',
  DIRECTORY: 'directory',
  SEEDERS: 'seeders',
  PUBLISH_DATE: 'publish_date',
  CREATED_AT: 'created_at',
  FREE: 'free',
  PACKAGE_FILE_COUNT: 'package_file_count',
  SEASON: 'season',
  EPISODE: 'episode',
  DISC: 'disc',
  RESOLUTION: 'resolution',
  VIDEO_CODEC: 'video_codec',
  AUDIO_CODEC: 'audio_codec',
  HDR_TYPE: 'hdr_type',
  AUDIO_CHANNELS: 'audio_channels',
  COLOR_DEPTH: 'color_depth',
  GROUP: 'group',
  SOURCE: 'source',
  RESOURCE_FORM: 'resource_form',
  PACKAGE_LAYOUT: 'package_layout',
  VERSION: 'version',
  LANGUAGE: 'language',
  SUBTITLE: 'subtitle',
  TAG: 'tag',
  SIZE: 'size',
  SITE: 'site',
})

export const DEFAULT_RESOURCE_TAGS = Object.freeze([
  ResourceTagType.UNMATCHED,
  ResourceTagType.DIRECTORY,
  ResourceTagType.SEEDERS,
  ResourceTagType.PUBLISH_DATE,
  ResourceTagType.CREATED_AT,
  ResourceTagType.FREE,
  ResourceTagType.PACKAGE_FILE_COUNT,
  ResourceTagType.SEASON,
  ResourceTagType.EPISODE,
  ResourceTagType.DISC,
  ResourceTagType.RESOLUTION,
  ResourceTagType.VIDEO_CODEC,
  ResourceTagType.AUDIO_CODEC,
  ResourceTagType.HDR_TYPE,
  ResourceTagType.AUDIO_CHANNELS,
  ResourceTagType.COLOR_DEPTH,
  ResourceTagType.GROUP,
  ResourceTagType.SOURCE,
  ResourceTagType.RESOURCE_FORM,
  ResourceTagType.PACKAGE_LAYOUT,
  ResourceTagType.VERSION,
  ResourceTagType.LANGUAGE,
  ResourceTagType.SUBTITLE,
  ResourceTagType.TAG,
  ResourceTagType.SIZE,
  ResourceTagType.SITE,
])
